const { writeFile } = require('fs');
const writeFileUsingFS = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
};

require('dotenv').config();

const target = './apps/angular-slack/src/environments/environment.prod.ts';
const firebase = JSON.parse(process.env.FIREBASE);
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${true},
    host: 'https://api-slack-ng.herokuapp.com',
    firebase: {
      apiKey: '${firebase.apiKey}',
      authDomain: '${firebase.authDomain}',
      databaseURL: '${firebase.databaseURL}',
      projectId: '${firebase.projectId}',
      storageBucket: '${firebase.storageBucket}',
      messagingSenderId: '${firebase.messagingSenderId}',
      appId: '${firebase.appId}',
      measurementId: '${firebase.measurementId}',
    },
  };
`;

writeFileUsingFS(target, environmentFileContent);
