const { writeFile } = require('fs');
const writeFileUsingFS = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
};
const { FIREBASE_KEY, AGORA_KEY, HOST } = process.argv[2];
const firebase = JSON.parse(Buffer.from(FIREBASE_KEY, 'base64').toString('ascii'));
const target = './apps/angular-slack/src/environments/environment.prod.ts';
const environmentFileContent = `
  // This file was autogenerated by dynamically running ${process.argv[1]}
  export const environment = {
    production: ${true},
    host: '${HOST}',
    firebase: {
      apiKey: '${firebase.apiKey}',
      authDomain: '${firebase.authDomain}',
      databaseURL: '${firebase.databaseURL}',
      projectId: '${firebase.projectId}',
      storageBucket: '${firebase.storageBucket}',
      messagingSenderId: '${firebase.messagingSenderId}',
      appId: '${firebase.appId}',
      measurementId: '${firebase.measurementId}',
    },
    webRtc: {
      AppID: '${AGORA_KEY}',
    },
  };
`;

if (!FIREBASE_KEY || !AGORA_KEY || !HOST) {
  throw new Error('Env variables are missed');
}

writeFileUsingFS(target, environmentFileContent);
