import { faGoogle } from '@fortawesome/free-brands-svg-icons';
import { faStar } from '@fortawesome/free-regular-svg-icons';
import {
  faCodeBranch,
  faEnvelope,
  faUnlockAlt,
  faPuzzlePiece,
  faUser,
  faUserCircle,
  faReply,
  faCode,
  faExchangeAlt,
  faPlus,
  faInfo,
  faCog,
  faStar as faStarSolid,
  faEdit,
  faFileUpload,
  faTimes,
  faMailBulk,
  faCircle,
  faCheck,
} from '@fortawesome/free-solid-svg-icons';

export const fontIcons = {
  faGoogle,
  faCodeBranch,
  faEnvelope,
  faUnlockAlt,
  faPuzzlePiece,
  faUser,
  faUserCircle,
  faReply,
  faCode,
  faExchangeAlt,
  faPlus,
  faInfo,
  faCog,
  faStar,
  faStarSolid,
  faEdit,
  faFileUpload,
  faTimes,
  faMailBulk,
  faCircle,
  faCheck,
};
