name: test-pull-request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install node_modules
        run: npm ci
      - name: Set env
        run: node set-env ${{ secrets }}
      - name: Run tests
        run: npm run test:prod
      - name: Test Coverage angular-slack
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/apps/angular-slack/coverage-summary.json
          title: angular-slack coverage
      - name: Test Coverage api
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/apps/api/coverage-summary.json
          title: api coverage
